### ISSUE TITLE
Practica 1 Prototipo de Interfaz gráfica

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/practicaprototipos-tadp-isag#2]
[PRACTICA1_PROTOTIPO.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-tadp-isag/files/8175356/PRACTICA1_PROTOTIPO.pdf)

**Comment by josealfredo79** [comment]
La calificación...?????

**Comment by josealfredo79** [comment]
Aqui debe ir

**Comment by josealfredo79** [comment]
Nuevamente la calificación???

**Comment by Yareli-Perez** [comment]
calificación = 95 = 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
